### ISSUE TITLE
Build a Dockerfile

### ISSUE THREAD

**Issue by rodowi** [rodowi/Paparazzo.js#32]
A docker container will make it easy to deploy on servers.

**Comment by augustinmerle** [comment]
Hi, you can fill my fork : Atc-it/Paparazzo.js
I've not test all but I seem good

**Comment by rodowi** [comment]
awesome
will test it ASAP

**Comment by rodowi** [comment]
build works, I just had to make an adjustment to `ADD . /paparazzo`

**Comment by rodowi** [comment]
hey @augustinmerle why did you add the following line?

```dockerfile
RUN chmod +x /paparazzo/node_modules/coffee-script/bin/coffee
```
