### ISSUE TITLE
How to use paparazzo

### ISSUE THREAD

**Issue by sunny200745** [rodowi/Paparazzo.js#5]
Hi wilhembot,
can u please let me know how to use paparazzo , from the docs it feels like have to do something on server side. i am totally client side developer and from demo.html i cant figure it out. Can u please help me out in this

thanks in advance

**Comment by williamkibira** [comment]
Hello, I was wondering , what if you wanted to handle many cameras at once or many vlc streams , how can this be presented out , probably as a factory of sorts .

**Comment by sp4ghet** [comment]
Can you show us how it works in javascript instead of coffeescript?

**Comment by defvol** [comment]
@Spaghet I guess you just need to find a coffee to Javascript converter and create a js version of https://github.com/rodowi/Paparazzo.js/blob/master/src/paparazzo.coffee

Try http://js2coffee.thomaskalka.de/#coffee2js
